### ISSUE TITLE
Could you share the dataset?

### ISSUE THREAD

**Issue by ghm** [agusgun/FakeImageDetector#9]
I used other dataset to run your program, but it's acc was much lower than yours.  Why?

**Comment by agusgun** [comment]
I do one additional step which is random deletion for downsampling that I don't mention in the notebook. 

If you follow the steps correctly your accuracy should be around 60-70%. You can try to do downsampling and the accuracy should be increased.

Another thing is I don't know whether the other dataset is the same with my dataset because the source is different and I don't think the one in Kaggle maintained.
